export const SAVE_FILM = 'SAVE_FILM';
export const EDIT_FILM_FIELD = 'EDIT_FILM_FIELD';
export const INITIALIZE_EDIT_FILM_FORM = 'INITIALIZE_EDIT_FILM_FORM';
export const CLEAR_EDIT_FILM_FORM = 'CLEAR_EDIT_FILM_FORM';